[versions]
agp = "8.13.0"
core = "3.5.3"
coreKtx = "1.17.0"
coreVersion = "3.5.4"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
lombok = "1.18.42"
lombokVersion = "1.18.30"
material = "1.13.0"
activity = "1.11.0"
constraintlayout = "2.2.1"
materialVersion = "1.11.0"
recyclerview = "1.4.0"
roomCommonJvm = "2.8.3"
roomCompilerVersion = "2.6.1"
roomRuntime = "2.8.3"
roomCompiler = "2.8.3"
googleAndroidLibrariesMapsplatformSecretsGradlePlugin = "2.0.1"
playServicesMaps = "19.2.0"
roomRuntimeVersion = "2.6.1"
zxingAndroidEmbedded = "4.3.0"

[libraries]
core = { module = "com.google.zxing:core", version.ref = "core" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
core-v354 = { module = "com.google.zxing:core", version.ref = "coreVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
lombok-v11830 = { module = "org.projectlombok:lombok", version.ref = "lombokVersion" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
material-v1110 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
room-common-jvm = { group = "androidx.room", name = "room-common-jvm", version.ref = "roomCommonJvm" }
room-compiler-v261 = { module = "androidx.room:room-compiler", version.ref = "roomCompilerVersion" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "roomRuntime" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "roomCompiler" }
play-services-maps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "playServicesMaps" }
room-runtime-v261 = { module = "androidx.room:room-runtime", version.ref = "roomRuntimeVersion" }
zxing-android-embedded = { module = "com.journeyapps:zxing-android-embedded", version.ref = "zxingAndroidEmbedded" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
google-android-libraries-mapsplatform-secrets-gradle-plugin = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "googleAndroidLibrariesMapsplatformSecretsGradlePlugin" }

